/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Sun Sep 29 18:14:50 2019. */

#include "pb_message.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t device_information_fields[5] = 
{
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, device_information_t, device_type, device_type, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, device_information_t, device_version, device_type, 0),
    PB_FIELD(  3, UENUM   , SINGULAR, STATIC  , OTHER, device_information_t, device_state, device_version, 0),
    PB_FIELD(  4, STRING  , SINGULAR, STATIC  , OTHER, device_information_t, algorithm_version, device_state, 0),
    PB_LAST_FIELD
};

const pb_field_t mqtt_server_configure_fields[6] = 
{
    PB_FIELD(  1, BOOL    , SINGULAR, STATIC  , FIRST, mqtt_server_configure_t, domain_name_flag, domain_name_flag, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, mqtt_server_configure_t, address, domain_name_flag, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, mqtt_server_configure_t, port, address, 0),
    PB_FIELD(  4, STRING  , SINGULAR, STATIC  , OTHER, mqtt_server_configure_t, username, port, 0),
    PB_FIELD(  5, STRING  , SINGULAR, STATIC  , OTHER, mqtt_server_configure_t, password, username, 0),
    PB_LAST_FIELD
};

const pb_field_t device_upgrade_fields[2] = 
{
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, device_upgrade_t, oad_address, oad_address, 0),
    PB_LAST_FIELD
};

const pb_field_t device_data_fields[13] = 
{
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, device_data_t, ble_mac, ble_mac, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, device_data_t, ble_packet_number, ble_mac, 0),
    PB_FIELD(  3, BOOL    , SINGULAR, STATIC  , OTHER, device_data_t, ble_charging_state, ble_packet_number, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, device_data_t, ble_battery_level, ble_charging_state, 0),
    PB_FIELD(  5, FLOAT   , REPEATED, STATIC  , OTHER, device_data_t, raw_temperature, ble_battery_level, 0),
    PB_FIELD(  6, FLOAT   , REPEATED, STATIC  , OTHER, device_data_t, algorithm_temperature, raw_temperature, 0),
    PB_FIELD(  7, UINT32  , SINGULAR, STATIC  , OTHER, device_data_t, algorithm_state, algorithm_temperature, 0),
    PB_FIELD(  8, UINT32  , SINGULAR, STATIC  , OTHER, device_data_t, algorithm_gesture, algorithm_state, 0),
    PB_FIELD(  9, BOOL    , SINGULAR, STATIC  , OTHER, device_data_t, algorithm_predict_state, algorithm_gesture, 0),
    PB_FIELD( 10, SINT32  , SINGULAR, STATIC  , OTHER, device_data_t, ble_rssi, algorithm_predict_state, 0),
    PB_FIELD( 11, SINT32  , SINGULAR, STATIC  , OTHER, device_data_t, wifi_rssi, ble_rssi, 0),
    PB_FIELD( 12, STRING  , SINGULAR, STATIC  , OTHER, device_data_t, current_time, wifi_rssi, 0),
    PB_LAST_FIELD
};

const pb_field_t ble_state_fields[5] = 
{
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, ble_state_t, ble_mac, ble_mac, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, ble_state_t, ble_device_version, ble_mac, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, ble_state_t, ble_device_type, ble_device_version, 0),
    PB_FIELD(  4, BOOL    , SINGULAR, STATIC  , OTHER, ble_state_t, ble_online_state, ble_device_type, 0),
    PB_LAST_FIELD
};

const pb_field_t device_state_fields[2] = 
{
    PB_FIELD(  1, BOOL    , SINGULAR, STATIC  , FIRST, device_state_t, online_state, online_state, 0),
    PB_LAST_FIELD
};



/* @@protoc_insertion_point(eof) */
